# [NumPy](https://numpy.org)

NumPy è una libreria fondamentale per eseguire calcoli vettoriali e matriciali in Python. Fornisce diversi oggetti, tra cui vettori multidimensionali, e numerose operazioni di algebra lineare eseguibili su tali vettori.  

NumPy non è un modulo predefinito di Python pertanto va installato separatamente.

Il package manager per la distribuzione Anaconda Python è il comando `conda`. 
Con il comando `conda install pacchetto` si può installare un nuovo pacchetto nel proprio ambiente base.

Il comando `conda` non va eseguito nel notebook poiché non è un comando di python ma va eseguito in un terminale. In Jupyter Notebook, è possibile utilizzare il punto esclamativo `!` per eseguire comandi come se stessimo usando il terminale.

In [1]:
# L'opzione -y serve per accettare eventuali prompt del programma
# di installazione
import sys
!conda install numpy -y --prefix {sys.prefix}

Jupyter detected...
2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.3.2
    latest version: 26.5.0

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.



Come abbiamo già visto il comando `import` ci permette di importare un modulo all'interno del nostro programma. Inoltre utilizzando il comando `as` possiamo  riferirci al modulo che si sta importando con il nome che definiamo.

In [2]:
import numpy

In [3]:
numpy.array([0, 1])

array([0, 1])

In [4]:
import numpy as np

In [5]:
np.array([0, 1])

array([0, 1])

Un vettore $n$-dimensionale (`ndarray`) è usato per contenere elementi ordinati tutti dello stesso tipo.

In [7]:
vettore = np.array([1, 2, 3])
vettore

array([1, 2, 3])

In [8]:
type(vettore), isinstance(vettore, np.ndarray)

(numpy.ndarray, True)

La dimensione di un vettore è definito dalla suo attributo `shape`, il quale è una tupla di $n$ interi non-negativi che specifica il numero di elementi in ogni dimensione.

In [9]:
# vettore è un vettore 1-dimensionale con 3 elementi
vettore.shape

(3,)

In [10]:
# matrice è un vettore 2-dimensionale (matrice) con 2 righe e 3 colonne
matrice = np.array([(1, 2, 3), (4, 5, 6)])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(matrice)

numpy.ndarray

In [12]:
matrice.shape

(2, 3)

L'attributo `dtype` contiene il tipo degli oggetti contenuti nel vettore.

In [13]:
# Vettore contiene interi in base 64
vettore.dtype

dtype('int64')

In [14]:
vettore_float = np.array([1.2, 2.5, 7.8])
vettore_float

array([1.2, 2.5, 7.8])

In [15]:
# È sempre un'istanze di ndarray
type(vettore_float)

numpy.ndarray

In [16]:
# Ma il suo dtype è float64 
vettore_float.dtype

dtype('float64')

Il `dtype` può essere specificato quando si inizializza un oggetto di tipo `ndarray`

In [18]:
# Senza specificare il dtype sarebbe int 
# ma forziamo la conversione a float
vettore_float = np.array([0, 1, 2], dtype = float)

In [19]:
vettore_float

array([0., 1., 2.])

In [20]:
vettore_float.dtype

dtype('float64')

NumPy mette a disposizone parecchie funzioni per creare vettori speciali.

`numpy.zeros(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, con tutti gli elementi uguali a zero.

In [21]:
mat = np.zeros(2, 2)

TypeError: Cannot interpret '2' as a data type

In [22]:
# Una matrice 2x2 di zeri con dtype float 
mat = np.zeros((2, 2))
print(mat, mat.shape, mat.dtype)

[[0. 0.]
 [0. 0.]] (2, 2) float64


`numpy.ones(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, con tutti gli elementi uguali a uno.

In [23]:
# Una matrice 3x4 di zeri con dtype int 
mat = np.ones((3, 4), dtype = int)
print(mat, mat.shape, mat.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (3, 4) int64


`numpy.empty(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, senza inizializzare gli elementi.

In [25]:
# Una matrice 4x1 di elementi non inizializzati con dtype float 
e = np.empty((4, 1))
e[0, 0]

np.float64(0.0)

Comunemente anche se la classe `ndarray` permette di istanziare vettori di 
ogni dimensione tipicamente ci si riferisce alle diverse dimensioni in modo diverso:

- 0D: scalare
- 1D: vettore
- 2D: matrice
- 3D+: tensore

In [26]:
# Un tensore 2x3x4 con tutti gli elementi a 1
tensore = np.ones((2, 3, 4))
tensore

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Gli oggetti di tipo `ndarray` possono essere indicizzati con la sintassi standard di Python, ovvero `array[index]` come nel caso delle liste.

In [27]:
vettore

array([1, 2, 3])

In [30]:
# L'elemento di posto 0
vettore[0]

np.int64(1)

In [31]:
# Gli elementi dal secondo in poi
vettore[1:]

array([2, 3])

In [32]:
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [33]:
# L'elemento di posto 0 è la prima riga
matrice[0]

array([1, 2, 3])

In [34]:
# L'elemento di posto 1 è la seconda riga
matrice[1]

array([4, 5, 6])

In [36]:
# Per estrarre un solo elemento dobbiamo usare due indici 
# uno per ogni dimensione
matrice[0][1]

np.int64(2)

In [37]:
# Equivalentemente in una sola parentesi
matrice[0, 1]

np.int64(2)

In [38]:
# Estrae la seconda colonna della matrice
matrice[:, 1]

array([2, 5])

In [39]:
# Estrae la prima riga della matrice
matrice[0, :]

array([1, 2, 3])

In [40]:
# Estrae la sottomatrice data dalla seconda e terza colonna
matrice[:, 1:3]

array([[2, 3],
       [5, 6]])

In [41]:
# Estrae la sottomatrice data dalla seconda e terza colonna
matrice[:, 1:]

array([[2, 3],
       [5, 6]])

Con gli `ndarrray` si possono eseguire anche indicizzazioni più complesse per esempio usando le liste.

In [42]:
vettore

array([1, 2, 3])

In [44]:
# Nuovo vettore che contiene gli elementi estratti 
# da vettore usando gli indici della lista
vettore[[0, 0, 1, 0]]

array([1, 1, 2, 1])

In [45]:
l = [1, 2, 3]

In [46]:
l[1:]

[2, 3]

In [47]:
l[0]

1

In [48]:
# La stessa cosa non si può fare con le liste
l[[0, 0, 1, 0]]

TypeError: list indices must be integers or slices, not list

In [51]:
vettore = np.array([1,3,1,0,2,4])

In [52]:
vettore >= 2

array([False,  True, False, False,  True,  True])

In [53]:
vettore[vettore >= 2]

array([3, 2, 4])

Ai vettori si possono applicare gli operaratori di confronto: se si confronta un vettore con uno scalare si ottiene un vettore contenente i confronti elemento per elemento.

In [54]:
x = np.array([20, 30, 40, 50])
x

array([20, 30, 40, 50])

In [55]:
x > 35

array([False, False,  True,  True])

Vettori boolenni come quello appena ottenuto possono a loro volta essere usati per indicizzare un vettore della medesima dimesione.

In [56]:
# Estraiamo il sottovettore degli elementi maggiori di 35
x[x > 35]

array([40, 50])

In [57]:
# Stessa cosa con una lista di booleani
x[[False, False,  True,  True]]

array([40, 50])

È possibile assegare un valore ad un sottoinsieme di un `ndarray`

In [58]:
tensore

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [59]:
tensore.shape

(2, 3, 4)

In [60]:
tensore[0, 0, 2] = 5
tensore

array([[[1., 1., 5., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [61]:
tensore[0, 0, 2:] = 5
tensore

array([[[1., 1., 5., 5.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [62]:
tensore[0, 0:2, 2:] = 5
tensore

array([[[1., 1., 5., 5.],
        [1., 1., 5., 5.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

[`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) è l'analogo in Numpy di `range`.

In [63]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [66]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`numpy.linspace(a, b, n)` restituisce un vettore avente un specifico numero di elementi `n` equispaziati su un certo intervallo [`a`,`b`].

In [67]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [72]:
np.linspace(0, 8, 5)

array([0., 2., 4., 6., 8.])

Di deafult il valore di `b` è incluso con `endpoint=False` si ottiene il seguente risultato.

In [73]:
np.linspace(0, 8, 5, endpoint = False)

array([0. , 1.6, 3.2, 4.8, 6.4])

In [74]:
np.linspace(0, 8, 9)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

### Operazioni fra vettori

Con gli `ndarray` si possono eseguire tutte le operazioni dell'algebra vettoriale.

In [75]:
v1 = np.array([1, 2, 3])
v2 = np.array([1.2, 2.5, 7.8])

Sommando due vettori si ottiene la somma vettoriale fra i due che differeisce da quanto visto per le liste

In [78]:
v1 + v2

array([ 2.2,  4.5, 10.8])

In [77]:
list(v1) + list(v2)

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.float64(1.2),
 np.float64(2.5),
 np.float64(7.8)]

Per sommare due liste come se fossero vettori dovremmo usare un ciclo for o una list comprehension

In [79]:
somma = []
for i in range(len(v1)):
    somma.append(v1[i] + v2[i])
somma

[np.float64(2.2), np.float64(4.5), np.float64(10.8)]

In [80]:
[v1[i] + v2[i] for i in range(len(v1))]

[np.float64(2.2), np.float64(4.5), np.float64(10.8)]

Come la somma tutte le altre opeazioni aritmetiche vengono eseguite elemento per elemento

In [81]:
v1 * v2

array([ 1.2,  5. , 23.4])

In [82]:
v1 - v2

array([-0.2, -0.5, -4.8])

In [83]:
v1 / v2

array([0.83333333, 0.8       , 0.38461538])

In [86]:
vettore = np.array([1,2,3])
vettore

array([1, 2, 3])

In [85]:
matrice

array([[1, 2, 3],
       [4, 5, 6]])

Fintanto che le shape di due vettori sono compatibili anche se non uguali gli operatori aritmetici continuano ad essere utilizzabili con risultati spesso utili

In [87]:
print(matrice.shape, vettore.shape)

(2, 3) (3,)


Qui vettore viene considerato come vettore riga (shape = (1, 3)) e quindi la sottrazzione funziona per righe poiché le dimensioni di colonna coincidono.

In [88]:
# sottraiamo (2, 3) con (1, 3)
matrice - vettore

array([[0, 0, 0],
       [3, 3, 3]])

In [91]:
# Invece le shape (3, 3) e (2, 3) non sono compatibili
np.zeros((3, 3)) - np.zeros((2, 3))

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

NumPy include al suo interno diverse costanti predefinite, come `Inf` e `pi`.

In [92]:
np.pi

3.141592653589793

In [93]:
np.inf

inf

In [94]:
type(np.inf)

float

In [95]:
np.e

2.718281828459045

Al suo interno poi troviamo le funzioni matematematiche per esempio quelle trigonometriche quali $\sin(x)$ e $\cos(x)$.

In [96]:
np.cos(0)

np.float64(1.0)

In [97]:
np.sin(0)

np.float64(0.0)

Come abbiamo detto le operazioni aritmetiche lavorano elemento per elemento. 
Ma nel caso delle matrici il prodotto matriciale non è quello elemento per elemento.

In algebra lineare se due matrici $A$ di dimensioni $n\times m$ e $B$ di dimensioni 
$m \times p$ vengono moltiplicate la matrice prodotto di dimensioni $n\times p$ si calcola con
$$
(A \cdot B)_{ij} = \biggl(\sum_{k=1}^m a_{ik} b_{kj}\biggr) 
$$

In [98]:
# Definiamo due matrici 2x2
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [99]:
A, B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [100]:
A + B

array([[3, 1],
       [3, 5]])

\* produce il prodotto elemento per elemento (se le shape sono compatibili)

In [101]:
A * B

array([[2, 0],
       [0, 4]])

@ produce il prodotto matriciale (se le matrici sono moltiplicabili)

In [102]:
A @ B

array([[5, 4],
       [3, 4]])

La stessa cosa si può ottenere anche con le funzioni `matmul` o `dot` del modulo NumPy

In [103]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [104]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

Nel caso di vettori dimensionali con $n$ elementi invece `dot` restituisce il prodotto scalare
$$
<a, b> = \sum_{i=1}^n a_i b_i
$$

In [105]:
v1, v2

(array([1, 2, 3]), array([1.2, 2.5, 7.8]))

In [106]:
np.dot(v1, v2)

np.float64(29.599999999999998)

Nella libreria sono poi definite molte funzioni (che possono essere chiamate anche come metodi delle istaze di `ndarray`) per il calcolo di funzioni di natura statistica.

In [107]:
# Minimo
np.min(vettore), vettore.min()

(np.int64(1), np.int64(1))

In [108]:
# Massimo
np.max(vettore), vettore.max()

(np.int64(3), np.int64(3))

In [109]:
# Media aritmetica
np.mean(vettore), vettore.mean()

(np.float64(2.0), np.float64(2.0))

In [110]:
# Deviazione standard
np.std(vettore), vettore.std()

(np.float64(0.816496580927726), np.float64(0.816496580927726))

In [111]:
# Varianza
np.var(vettore), vettore.var()

(np.float64(0.6666666666666666), np.float64(0.6666666666666666))

Per esempio la funzione che calcola la mediana invece non è disponibile come metodo di classe poiché in generale non è definita per i vettori multidimensionali.

In [112]:
vettore.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [113]:
# Solo per vettori 1-dimensionali
np.median(vettore)

np.float64(2.0)

Il metodo `reshape` cambia la shape del vettore senza cambiare i dati contenuti in esso.

In [114]:
vec = np.arange(12)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [115]:
vec.shape

(12,)

In [116]:
# Cambiamo la shape di vec da (12, 1) a (3, 4)
mat = vec.reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [117]:
mat.shape

(3, 4)

In [118]:
mat.sum()

np.int64(66)

I metodi `min`, `max`, `sum`... possono essere calcolati solo su alcune dimensioni di un `ndarray`.

In [119]:
# Somma per colonne ovvero lungo la prima dimensione
mat.sum(axis = 0)

array([12, 15, 18, 21])

In [124]:
# Somma per righe ovvero lungo la seconda dimensione
mat.sum(axis = 1)

array([ 6, 22, 38])

Si può passare -1 al metodo reshape per far calcolare a NumPy il numero di elementi in quella dimensione

In [125]:
# Vogliamo mat con una shape di una sola dimensione quindi di 12 elementi
vec2 = mat.reshape(-1)
vec2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [128]:
mat.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

`numpy.ravel` permette di 'appiattire' un array ad una sola dimansione.

In [129]:
# Equivalente a mat.reshape(-1)
np.ravel(mat)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Il modulo `random` che abbiamo già introdotto è usatro per la generazione di numeri pseudo casuali.

In [130]:
import random

In [135]:
random.randint(0, 10)

8

Anche NumPy ha un sottomodulo random che permette di generare vettori i cui elementi sono numeri pseuso casuali.

`numpy.random.normal(mean=0.0, std=1.0, shape)` genera vettori estratti da una distribuzione Gaussiana.
$$
\mathcal{N}(\mu, \sigma^2)
$$

In [137]:
# Vettore di dimensione 10 estratto da N(0,1) normale standard
np.random.normal(0, 1, (2, 3))

array([[ 0.92367098, -0.04268719, -0.53223722],
       [ 1.66029675,  0.0600349 , -1.29556465]])

In [138]:
mu = 4
sigma = 1

sample = np.random.normal(mu, sigma, 100)
sample

array([3.39581163, 3.73842168, 3.58275873, 4.31097811, 4.79881016,
       4.60445915, 4.07962852, 5.82657787, 4.80913052, 4.17772415,
       4.09551208, 3.84346648, 4.63062838, 4.40206006, 5.18346722,
       4.27810128, 3.73638639, 3.6738941 , 3.2308906 , 4.32631234,
       3.30401911, 3.14148549, 4.61757671, 2.86586684, 3.33058404,
       3.47325731, 4.12989286, 5.91004725, 3.12138776, 3.42800862,
       6.77590054, 3.81018586, 6.52664851, 3.00307856, 4.61692159,
       3.35215535, 2.58246123, 4.36712389, 5.58403476, 2.97479445,
       4.9366095 , 3.4895897 , 4.34552539, 5.43292618, 3.83212066,
       5.55194886, 3.28710808, 5.31074187, 3.21535872, 3.3116223 ,
       5.52084547, 2.92719023, 3.01946357, 4.36216194, 2.5980749 ,
       4.5145241 , 3.85185915, 4.68479367, 2.34620475, 2.92092044,
       4.84864261, 3.9017067 , 3.93831868, 5.93023873, 4.8100703 ,
       2.54227915, 5.68290048, 5.28331499, 3.59234556, 4.23270611,
       4.83680077, 4.89095938, 4.58472494, 4.20598   , 4.08916

Se calcoliamo le stime campionarie di media e deviazione standard otteniamo i risultati attesi

In [139]:
sample.mean(), sample.std()

(np.float64(4.115349661943015), np.float64(1.0233064277673416))

La stima diventa più precisa all'aumentare della dimensione del campione

In [140]:
sample = np.random.normal(mu, sigma, 10000)
sample.mean(), sample.std()

(np.float64(4.0017668555077845), np.float64(0.9959114086075864))

`np.random.uniform(low=0.0, high=1.0, size=None)` genera vettori estratti da una distribuzione Uniforme.
$$
\mathcal{U}([low, high))
$$

In [141]:
# Vettore di dimensione 10 estratto da U(0,1) normale standard
np.random.uniform(0, 1, 10)

array([0.01142186, 0.75176648, 0.63361771, 0.77166474, 0.63594255,
       0.56011445, 0.88252835, 0.96373857, 0.88108657, 0.92554467])

np.random.uniform(0, 1, (5, 5))

`np.random.randint, size=None)`

In [146]:
np.random.randint(0, 10, (10, 10))

array([[6, 2, 4, 3, 6, 3, 2, 5, 1, 9],
       [7, 5, 7, 1, 6, 6, 9, 9, 2, 2],
       [6, 0, 6, 2, 9, 6, 2, 6, 7, 8],
       [5, 2, 9, 8, 5, 2, 0, 0, 5, 9],
       [7, 7, 9, 7, 0, 0, 4, 8, 4, 7],
       [9, 2, 6, 7, 8, 6, 7, 7, 5, 3],
       [2, 7, 0, 6, 2, 7, 0, 7, 9, 5],
       [5, 1, 9, 7, 5, 3, 2, 5, 0, 9],
       [8, 5, 0, 5, 0, 8, 1, 7, 0, 1],
       [8, 4, 8, 0, 2, 4, 1, 7, 6, 7]])

## Esercizi

Definire la funzione `inversa`. Tale funzione prende in ingresso una matrice e 
- per prima cosa controlla che sia una matrice e che sia quadrata, altrimenti restituisce un errore e termina la funzione restituendo `None`. 
- calcola il determinante della matrice con la funzione `numpy.linalg.det(matrice)`
- se il determinante è maggiore di 0.0001 calcola la matrice inversa con la funzione `numpy.linalg.inv(matrice)` e la restituisce come output.

In [156]:
def inversa(matrice):

    if not isinstance(matrice, np.ndarray):
        print("Errore matrice deve essere un ndarray.")
        return None

    if not len(matrice.shape) == 2:
        print("Errore matrice deve essere effettivamente una matrice.")
        return None

    if matrice.shape[0] != matrice.shape[1]:
        print("Errore matrice deve essere quadrata.")
        return None

    det = np.linalg.det(matrice)

    if np.abs(det) >= 0.0001:
        return np.linalg.inv(matrice)
    else:
        print("Errore matrice non è invertibile.")
        return None

In [161]:
# Invertibile
A = np.array([[1, 2], [-1, 3]])
Ainv = inversa(A)
print(Ainv)

[[ 0.6 -0.4]
 [ 0.2  0.2]]


In [162]:
# Non invertibile
A = np.array([[1, 2], [1, 2]])
Ainv = inversa(A)
print(Ainv)

Errore matrice non è invertibile.
None


In [163]:
# Non quadrata
A = np.array([[1, 2, 3], [1, 2, 3]])
Ainv = inversa(A)
print(Ainv)

Errore matrice deve essere quadrata.
None


In [164]:
# Non matrice
A = np.array([1,2,3])
Ainv = inversa(A)
print(Ainv)

Errore matrice deve essere effettivamente una matrice.
None


In [165]:
# Non Numpy
A = [1,2,3]
Ainv = inversa(A)
print(Ainv)

Errore matrice deve essere un ndarray.
None


Definite le matrici e i vettori
$$
A = \begin{pmatrix}
    0 & 1 & 2\\
    -1 & 2 & 1\\
    1 & 0 & -2\\
    \end{pmatrix}\quad
B = \begin{pmatrix}
3 & 2\\
0 & -1\\
1 & 1 \\
\end{pmatrix}\quad
v = \begin{pmatrix}
1\\
-1\\
1 \\
\end{pmatrix}\quad
w = \begin{pmatrix}
0\\
-1\\
2 \\
\end{pmatrix}
$$
calcolare $AB$, $Av$, $Av + w$ e $<Av, Aw>$

Istanziare un tensore di dimensioni (5, 3, 3) le cui entrate sono estratte da una distribuzione normale standard.

Dopodiché sostituire tutti e soli i valori negativi con 0.

Calcolare media, varianza e mediana del tensore ottenuto.

Scrivere una funzione che:
- prende in ingresso una matrice $X$ di dimensione ($n$, $m$)
- restituisce una matrice $Y$ di dimensione ($n$, 2) contenente le medie e le varianza per riga di $X$.

Creare una classe `Titolo` che rappresenta un titolo misurato anno per anno. La classe dovrà avere i seguenti attributi:
- `nome`: string, nome del titolo
- `titolo`: numpy.array, vettore contenente le rilevazioni del titolo
- `periodo`: numpy.array, vettore contenente i periodi corrispondenti alle rilevazioni

e i seguenti metodi:
- `__len__` calcola la lunghezza del titolo.
- `indice_base_fissa(base)` che restituisce l'indice a base fissa calcolato con base il periodo `base`.
- `indice_base_mobile()` che restituisce l'indice a base mobile del titolo.
- `variazione_media(t1, t2)` che restituisce la variazione media del titolo fra il periodo `t1` e il periodo `t2`. 

Definire poi una funzione che, preso in ingresso un `Titolo` resituisca la matrice $M$ di dimensione ($n$, 4) con $n$ la lunghezza del titolo. La matrice $M$ contiene nella prima colonna il periodo, nella seconda il titolo, nella terza l'indice a base fissa (con base il primo periodo) e nella quarta l'indice a base mobile. 