# [NumPy](https://numpy.org)

NumPy è una libreria fondamentale per eseguire calcoli vettoriali e matriciali in Python. Fornisce diversi oggetti, tra cui vettori multidimensionali, e numerose operazioni di algebra lineare eseguibili su tali vettori.  

NumPy non è un modulo predefinito di Python pertanto va installato separatamente.

Il package manager per la distribuzione Anaconda python è il comando `conda`. 
Con il comando `conda install pacchetto` si può installare un nuovo pacchetto nel proprio ambiente base.

Il comando `conda` non va eseguito nel notebook poiché non è un comando di python ma va eseguito in un terminale. In Jupyter Notebook, è possibile utilizzare il punto esclamativo `!` per eseguire comandi come se stessimo usando il terminale.

In [1]:
# L'opzione -y serve per accettare eventuali prompt del programma
# di installazione
import sys
!conda install numpy -y --prefix {sys.prefix}

Channels:
 - defaults
Platform: linux-64
doneecting package metadata (repodata.json): - 
doneing environment: | 

# All requested packages already installed.



Come abbiamo già visto il comando `import` ci permette di importare un modulo all'interno del nostro programma. Inoltre utilizzando il comando `as` possiamo  riferirci al modulo che si sta importando con il nome che definiamo.

In [2]:
import numpy

In [3]:
numpy.array([0, 1])

array([0, 1])

In [4]:
import numpy as np

In [5]:
np.array([0, 1])

array([0, 1])

Un vettore $n$-dimensionale (`ndarray`) è usato per contenere $n$ elementi ordinati tutti dello stesso tipo.

In [6]:
vettore = np.array([1, 2, 3])
vettore

array([1, 2, 3])

In [7]:
type(vettore), isinstance(vettore, np.ndarray)

(numpy.ndarray, True)

La dimensione di un vettore è definito dalla suo attributo `shape`, il quale è una tupla di $n$ interi non-negativi che specifica il numero di elementi in ogni dimensione.

In [8]:
# a è un vettore 1-dimensionale con 3 elementi
vettore.shape

(3,)

In [9]:
# b è un vettore 2-dimensionale (matrice) con 2 righe e 3 colonne
matrice = np.array([(1, 2, 3), (4, 5, 6)])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
type(matrice)

numpy.ndarray

In [11]:
matrice.shape

(2, 3)

L'attributo `dtype` contiene il tipo degli oggetti contenuti nel vettore.

In [12]:
# Vettore contiene interi in base 64
vettore.dtype

dtype('int64')

In [13]:
vettore_float = np.array([1.2, 2.5, 7.8])
vettore_float

array([1.2, 2.5, 7.8])

In [14]:
# È sempre un'istanze di ndarray
type(vettore_float)

numpy.ndarray

In [15]:
# Ma il suo dtype è float64 
vettore_float.dtype

dtype('float64')

Il `dtype` può essere specificato quando si inizializza un oggetto di tipo `ndarray`

In [16]:
# Senza specificare il dtype sarebbe int 
# ma forziamo la conversione a float
vettore_float = np.array([0, 1, 2], dtype = float)

In [17]:
vettore_float

array([0., 1., 2.])

In [18]:
vettore_float.dtype

dtype('float64')

NumPy mette a disposizone parecchie funzioni per creare vettori speciali.

`numpy.zeros(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, con tutti gli elementi uguali a zero.

In [19]:
mat = np.zeros(2, 2)

TypeError: Cannot interpret '2' as a data type

In [20]:
# Una matrice 2x2 di zeri con dtype float 
mat = np.zeros((2, 2))
print(mat, mat.shape, mat.dtype)

[[0. 0.]
 [0. 0.]] (2, 2) float64


`numpy.ones(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, con tutti gli elementi uguali a uno.

In [21]:
# Una matrice 3x4 di zeri con dtype int 
mat = np.ones((3, 4), dtype = int)
print(mat, mat.shape, mat.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (3, 4) int64


`numpy.empty(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, senza inizializzare gli elementi.

In [22]:
# Una matrice 3x4 di elementi non inizializzati con dtype float 
e = np.empty((4, 1))
e[0]

array([0.])

Comunemente anche se la classe `ndarray` permette di istanziare vettori di 
ogni dimensione tipicamente ci si riferisce alle diverse dimensioni in modo diverso:

- 0D: scalare
- 1D: vettore
- 2D: matrice
- 3D+: tensore

In [23]:
# Un tensore 2x3x4 con tutti gli elementi a 1
tensore = np.ones((2, 3, 4))
tensore

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Gli oggetti di tipo `ndarray` possono essere indicizzati con la sintassi standard di Python, ovvero `array[index]` come nel caso delle liste.

In [24]:
vettore

array([1, 2, 3])

In [27]:
# L'elemento di posto 0
vettore[0]

np.int64(1)

In [28]:
# Gli elementi dal secondo in poi
vettore[1:]

array([2, 3])

In [29]:
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# L'elemento di posto 0 è la prima riga
matrice[0]

array([1, 2, 3])

In [31]:
# L'elemento di posto 1 è la seconda riga
matrice[1]

array([4, 5, 6])

In [32]:
# Per estrarre un solo elemento dobbiamo usare due indici 
# uno per ogni dimensione
matrice[0][1]

np.int64(2)

In [33]:
# Equivalentemente in una sola parentesi
matrice[0, 1]

np.int64(2)

In [34]:
# Estrae la seconda colonna della matrice
matrice[:, 1]

array([2, 5])

In [35]:
# Estrae la prima riga della matrice
matrice[0, :]

array([1, 2, 3])

In [36]:
# Estrae la sottomatrice data dalla seconda e terza colonna
matrice[:, 1:3]

array([[2, 3],
       [5, 6]])

In [37]:
# Estrae la sottomatrice data dalla seconda e terza colonna
matrice[:, 1:]

array([[2, 3],
       [5, 6]])

Con gli `ndarrray` si possono eseguire anche indicizzazioni più complesse per esempio usando le liste.

In [38]:
vettore

array([1, 2, 3])

In [39]:
# Nuovo vettore che contiene gli elementi estratti 
# da vettore usando gli indici della lista
vettore[[0, 0, 1, 0]]

array([1, 1, 2, 1])

In [41]:
l = [1, 2, 3]

In [42]:
l[1:]

[2, 3]

In [43]:
l[0]

1

In [44]:
# La stessa cosa non si può fare con le liste
l[[0, 0, 1, 0]]

TypeError: list indices must be integers or slices, not list

In [45]:
vettore >= 2

array([False,  True,  True])

In [46]:
vettore[vettore >= 2]

array([2, 3])

Ai vettori si possono applicare gli operaratori di confronto: se si confronta un vettore con uno scalare si ottiene un vettore contenente i confronti elemento per elemento.

In [47]:
x = np.array([20, 30, 40, 50])
x

array([20, 30, 40, 50])

In [48]:
x > 35

array([False, False,  True,  True])

Vettori boolenni come quello appena ottenuto possono a loro volta essere usati per indicizzare un vettore della medesima dimesione.

In [49]:
# Estraiamo il sottovettore degli elementi maggiori di 35
x[x > 35]

array([40, 50])

In [50]:
# Stessa cosa con una lista di booleani
x[[False, False,  True,  True]]

array([40, 50])

È possibile assegare un valore ad un sottoinsieme di un `ndarray`

In [51]:
tensore

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [52]:
tensore.shape

(2, 3, 4)

In [53]:
tensore[0, 0, 2] = 5
tensore

array([[[1., 1., 5., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [54]:
tensore[0, 0, 2:] = 5
tensore

array([[[1., 1., 5., 5.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [55]:
tensore[0, 0:2, 2:] = 5
tensore

array([[[1., 1., 5., 5.],
        [1., 1., 5., 5.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

[`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) è l'analogo in Numpy di `range`.

In [56]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [59]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`numpy.linspace(a, b, n)` restituisce un vettore avente un specifico numero di elementi `n` equispaziati su un certo intervallo [`a`,`b`].

In [60]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [63]:
np.linspace(0, 8, 5)

array([0., 2., 4., 6., 8.])

Di deafult il valore di `b` è incluso con `endpoint=False` si ottiene il seguente risultato.

In [64]:
np.linspace(0, 8, 5, endpoint = False)

array([0. , 1.6, 3.2, 4.8, 6.4])

In [66]:
np.linspace(0, 8, 9)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

### Operazioni fra vettori

Con gli `ndarray` si possono eseguire tutte le operazioni dell'algebra vettoriale.

In [67]:
v1 = np.array([1, 2, 3])
v2 = np.array([1.2, 2.5, 7.8])

Sommando due vettori si ottiene la somma vettoriale fra i due che differeisce da quanto visto per le liste

In [68]:
v1 + v2

array([ 2.2,  4.5, 10.8])

In [69]:
list(v1) + list(v2)

[np.int64(1),
 np.int64(2),
 np.int64(3),
 np.float64(1.2),
 np.float64(2.5),
 np.float64(7.8)]

Per sommare due liste come se fossero vettori dovremmo usare un ciclo for o una list comprehension

In [70]:
somma = []
for i in range(len(v1)):
    somma.append(v1[i] + v2[i])
somma

[np.float64(2.2), np.float64(4.5), np.float64(10.8)]

In [71]:
[v1[i] + v2[i] for i in range(len(v1))]

[np.float64(2.2), np.float64(4.5), np.float64(10.8)]

Come la somma tutte le altre opeazioni aritmetiche vengono eseguite elemento per elemento

In [72]:
v1 * v2

array([ 1.2,  5. , 23.4])

In [73]:
v1 - v2

array([-0.2, -0.5, -4.8])

In [74]:
v1 / v2

array([0.83333333, 0.8       , 0.38461538])

In [75]:
vettore

array([1, 2, 3])

In [76]:
matrice

array([[1, 2, 3],
       [4, 5, 6]])

Fintanto che le shape di due vettori sono compatibili anche se non uguali gli operatori aritmetici continuano ad essere utilizzabili con risultati spesso utili

In [77]:
print(matrice.shape, vettore.shape)

(2, 3) (3,)


Qui vettore viene considerato come vettore riga (shape = (1, 3)) e quindi la sottrazzione funziona per righe poiché le dimensioni di colonna coincidono.

In [78]:
# sottraiamo (2, 3) con (1, 3)
matrice - vettore

array([[0, 0, 0],
       [3, 3, 3]])

In [79]:
# Invece le shape (3, 3) e (2, 3) non sono compatibili
np.zeros((3, 3)) - np.zeros((2, 3))

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

NumPy include al suo interno diverse costanti predefinite, come `Inf` e `pi`.

In [80]:
np.pi

3.141592653589793

In [82]:
np.inf

inf

In [83]:
type(np.inf)

float

In [84]:
np.e

2.718281828459045

Al suo interno poi troviamo le funzioni matematematiche per esempio quelle trigonometriche quali $\sin(x)$ e $\cos(x)$.

In [85]:
np.cos(0)

np.float64(1.0)

In [86]:
np.sin(0)

np.float64(0.0)

Come abbiamo detto le operazioni aritmetiche lavorano elemento per elemento. 
Ma nel caso delle matrici il prodotto matriciale non è quello elemento per elemento.

In algebra lineare se due matrici $A$ di dimensioni $n\times m$ e $B$ di dimensioni 
$m \times p$ vengono moltiplicate la matrice prodotto di dimensioni $n\times p$ si calcola con
$$
(A \cdot B)_{ij} = \biggl(\sum_{k=1}^m a_{ik} b_{kj}\biggr) 
$$

In [87]:
# Definiamo due matrici 2x2
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [88]:
A, B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [89]:
A + B

array([[3, 1],
       [3, 5]])

\* produce il prodotto elemento per elemento (se le shape sono compatibili)

In [90]:
A * B

array([[2, 0],
       [0, 4]])

@ produce il prodotto matriciale (se le matrici sono moltiplicabili)

In [91]:
A @ B

array([[5, 4],
       [3, 4]])

La stessa cosa si può ottenere anche con le funzioni `matmul` o `dot` del modulo NumPy

In [92]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [93]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

Nel caso di vettori dimensionali con $n$ elementi invece `dot` restituisce il prodotto scalare
$$
<a, b> = \sum_{i=1}^n a_i b_i
$$

In [94]:
v1, v2

(array([1, 2, 3]), array([1.2, 2.5, 7.8]))

In [95]:
np.dot(v1, v2)

np.float64(29.599999999999998)

Nella libreria sono poi definite molte funzioni (che possono essere chiamate anche come metodi delle istaze di `ndarray`) per il calcolo di funzioni di natura statistica.

In [96]:
# Minimo
np.min(vettore), vettore.min()

(np.int64(1), np.int64(1))

In [97]:
# Massimo
np.max(vettore), vettore.max()

(np.int64(3), np.int64(3))

In [98]:
# Media aritmetica
np.mean(vettore), vettore.mean()

(np.float64(2.0), np.float64(2.0))

In [99]:
# Deviazione standard
np.std(vettore), vettore.std()

(np.float64(0.816496580927726), np.float64(0.816496580927726))

In [100]:
# Varianza
np.var(vettore), vettore.var()

(np.float64(0.6666666666666666), np.float64(0.6666666666666666))

Per esempio la funzione che calcola la mediana invece non è disponibile come metodo di classe poiché in generale non è definita per i vettori multidimensionali.

In [101]:
vettore.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [102]:
np.median(vettore)

np.float64(2.0)

Il metodo `reshape` cambia la shape del vettore senza cambiare i dati contenuti in esso.

In [103]:
vec = np.arange(12)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [104]:
vec.shape

(12,)

In [107]:
# Cambiamo la shape di vec da (12, 1) a (3, 4)
mat = vec.reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
mat.shape

(3, 4)

In [109]:
mat.sum()

np.int64(66)

I metodi `min`, `max`, `sum`... possono essere calcolati solo su alcune dimensioni di un `ndarray`.

In [110]:
# Somma per colonne ovvero lungo la prima dimensione
mat.sum(axis = 0)

array([12, 15, 18, 21])

In [111]:
# Somma per righe ovvero lungo la seconda dimensione
mat.sum(axis = 1)

array([ 6, 22, 38])

Si può passare -1 al metodo reshape per far calcolare a NumPy il numero di elementi in quella dimensione

In [112]:
# Vogliamo mat con una shape di una sola dimensione quindi di 12 elementi
vec2 = mat.reshape(-1)
vec2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [114]:
mat.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

`numpy.ravel` permette di 'appiattire' un array ad una sola dimansione.

In [115]:
# Equivalente a mat.reshape(-1)
np.ravel(mat)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Il modulo `random` che abbiamo già introdotto è usatro per la generazione di numeri pseudo casuali.

In [116]:
import random

In [117]:
random.randint(0, 10)

8

Anche NumPy ha un sottomodulo random che permette di generare vettori i cui elementi sono numeri pseuso casuali.

`numpy.random.normal(mean=0.0, std=1.0, shape)` genera vettori estratti da una distribuzione Gaussiana.
$$
\mathcal{N}(\mu, \sigma^2)
$$

In [121]:
# Vettore di dimensione 10 estratto da N(0,1) normale standard
np.random.normal(0, 1, 10)

array([-0.21754824,  1.0331202 ,  0.70636918, -1.04771002,  1.70726714,
        0.99920848, -1.15031289,  1.45835882,  0.52788055, -0.2223268 ])

In [122]:
mu = 4
sigma = 1

sample = np.random.normal(mu, sigma, 100)
sample

array([3.72419628, 4.30747748, 4.92407202, 4.23239013, 5.34755389,
       5.77393103, 4.77310999, 4.41175443, 3.19833489, 4.20931106,
       3.17994302, 4.14052698, 4.5343676 , 3.75688204, 4.09996398,
       4.23607401, 5.00930578, 4.05381125, 3.55617775, 4.23205431,
       4.31333552, 3.92567833, 5.80596067, 3.85230013, 4.5170012 ,
       4.62219479, 3.72200725, 5.99543907, 4.34286939, 3.35088644,
       4.22670125, 5.43786891, 2.93493948, 3.84846878, 3.62026989,
       3.57837932, 4.94761807, 5.43734692, 3.23696944, 3.86606983,
       3.12722214, 3.05246182, 3.57256187, 2.39400462, 4.9823712 ,
       4.1540362 , 4.96680375, 4.50866707, 5.29904308, 3.07699633,
       4.43097534, 2.74783278, 4.33892794, 3.97063511, 2.26052808,
       2.77598313, 1.77640098, 3.73009774, 3.87378384, 5.64390821,
       3.52704887, 3.5436286 , 4.97171241, 3.94652743, 4.53799235,
       2.84349724, 3.74489691, 6.01717533, 3.33097721, 3.56140487,
       4.06120198, 4.01546285, 3.93121508, 5.18295615, 3.28130

Se calcoliamo le stime campionarie di media e deviazione standard otteniamo i risultati attesi

In [123]:
sample.mean(), sample.std()

(np.float64(4.009467755089548), np.float64(0.9356633221965344))

La stima diventa più precisa all'aumentare della dimensione del campione

In [124]:
sample = np.random.normal(mu, sigma, 10000)
sample.mean(), sample.std()

(np.float64(3.9987669068411895), np.float64(0.9989787803876742))

`np.random.uniform(low=0.0, high=1.0, size=None)` genera vettori estratti da una distribuzione Uniforme.
$$
\mathcal{U}([low, high))
$$

In [125]:
# Vettore di dimensione 10 estratto da U(0,1) normale standard
np.random.uniform(0, 1, 10)

array([0.65102044, 0.49028021, 0.78764108, 0.45732775, 0.48037693,
       0.04896964, 0.21232831, 0.99739238, 0.89654833, 0.73923524])

In [126]:
np.random.uniform(0, 1, (5, 5))

array([[0.47803913, 0.35989675, 0.95864282, 0.98365554, 0.41225896],
       [0.38136755, 0.47325823, 0.46195452, 0.37161795, 0.17326982],
       [0.04944538, 0.01493967, 0.02002042, 0.43209366, 0.74532026],
       [0.51862861, 0.5892059 , 0.97426901, 0.74919987, 0.36584949],
       [0.83627808, 0.57603401, 0.74109701, 0.94844253, 0.23791931]])

In [127]:
np.random.randint(0, 10, 10)

array([8, 8, 6, 1, 9, 5, 9, 6, 9, 8])

## Esercizi

Definire la funzione `inversa`. Tale funzione prende in ingresso una matrice e 
- per prima cosa controlla che sia una matrice e che sia quadrata, altrimenti restituisce un errore e termina la funzione restituendo `None`. 
- calcola il determinante della matrice con la funzione `numpy.linalg.det(matrice)`
- se il determinante è maggiore di 0.0001 calcola la matrice inversa con la funzione `numpy.linalg.inv(matrice)` e la restituisce come output.

In [143]:
matrice0 = np.array([[1,2,3], [1,2,3]])
matrice1 = np.array([[1,2,3], [1,2,3], [1,2,3]])
matrice2 = np.arange(2,11).reshape(3,3)
matrice3 = np.random.normal(0, 1, (3,3))

In [137]:
def inversa(matrice):

    if len(matrice.shape) != 2 or matrice.shape[0] != matrice.shape[1]:
        print("Errore, l'input deve essere una matrice quadrata.")
        return None
    else:
        det = np.linalg.det(matrice)

        if det > 0.0001:
            inv = np.linalg.inv(matrice)
            return inv
        else:
            print("La matrice non è invertibile")
            return None    

In [140]:
result = inversa(matrice0)
result

Errore, l'input deve essere una matrice quadrata.


In [141]:
result = inversa(matrice1)
result

La matrice non è invertibile


In [144]:
result = inversa(matrice2)
result

La matrice non è invertibile


In [145]:
result = inversa(matrice3)
result

array([[-0.29492793, -0.36664441, -0.04944397],
       [ 1.38075542, -2.22082645, -1.26983605],
       [-0.84954165,  0.2472524 ,  1.57316802]])

Definite le matrici e i vettori
$$
A = \begin{pmatrix}
    0 & 1 & 2\\
    -1 & 2 & 1\\
    1 & 0 & -2\\
    \end{pmatrix}\quad
B = \begin{pmatrix}
3 & 2\\
0 & -1\\
1 & 1 \\
\end{pmatrix}\quad
v = \begin{pmatrix}
1\\
-1\\
1 \\
\end{pmatrix}\quad
w = \begin{pmatrix}
0\\
-1\\
2 \\
\end{pmatrix}
$$
calcolare $AB$, $Av$, $Av + w$ e $<Av, Aw>$

Istanziare un tensore di dimensioni (5, 3, 3) le cui entrate sono estratte da una distribuzione normale standard.

Dopodiché sostituire tutti e soli i valori negativi con 0.

Calcolare media, varianza e mediana del tensore ottenuto.

Scrivere una funzione che:
- prende in ingresso una matrice $X$ di dimensione ($n$, $m$)
- restituisce una matrice $Y$ di dimensione ($n$, 2) contenente le medie e le varianza per riga di $X$.

Creare una classe `Titolo` che rappresenta un titolo misurato anno per anno. La classe dovrà avere i seguenti attributi:
- `nome`: string, nome del titolo
- `titolo`: numpy.array, vettore contenente le rilevazioni del titolo
- `periodo`: numpy.array, vettore contenente i periodi corrispondenti alle rilevazioni

e i seguenti metodi:
- `__len__` calcola la lunghezza del titolo.
- `indice_base_fissa(base)` che restituisce l'indice a base fissa calcolato con base il periodo `base`.
- `indice_base_mobile()` che restituisce l'indice a base mobile del titolo.
- `variazione_media(t1, t2)` che restituisce la variazione media del titolo fra il periodo `t1` e il periodo `t2`. 

Definire poi una funzione che, preso in ingresso un `Titolo` resituisca la matrice $M$ di dimensione ($n$, 4) con $n$ la lunghezza del titolo. La matrice $M$ contiene nella prima colonna il periodo, nella seconda il titolo, nella terza l'indice a base fissa (con base il primo periodo) e nella quarta l'indice a base mobile. 