# [NumPy](https://numpy.org)

NumPy è una libreria fondamentale per eseguire calcoli vettoriali e matriciali in Python. Fornisce diversi oggetti, tra cui vettori multidimensionali, e numerose operazioni di algebra lineare eseguibili su tali vettori.  

NumPy non è un modulo predefinito di Python pertanto va installato separatamente.

Il package manager per la distribuzione Anaconda python è il comando `conda`. 
Con il comando `conda install pacchetto` si può installare un nuovo pacchetto nel proprio ambiente base.

Il comando `conda` non va eseguito nel notebook poiché non è un comando di python ma va eseguito in un terminale. In Jupyter Notebook, è possibile utilizzare il punto esclamativo `!` per eseguire comandi come se stessimo usando il terminale.

In [1]:
# L'opzione -y serve per accettare eventuali prompt del programma
# di installazione
import sys
!conda install numpy -y --prefix {sys.prefix}

Channels:
 - defaults
 - conda-forge
Platform: linux-64
Solving environment: done

# All requested packages already installed.



Come abbiamo già visto il comando `import` ci permette di importare un modulo all'interno del nostro programma. Inoltre utilizzando il comando `as` possiamo  riferirci al modulo che si sta importando con il nome che definiamo.

In [2]:
import numpy

In [3]:
numpy.array([0, 1])

array([0, 1])

In [5]:
import numpy as np

In [6]:
np.array([0, 1])

array([0, 1])

Un vettore $n$-dimensionale (`ndarray`) è usato per contenere $n$ elementi ordinati tutti dello stesso tipo.

In [7]:
vettore = np.array([1, 2, 3])
vettore

array([1, 2, 3])

In [8]:
type(vettore), isinstance(vettore, np.ndarray)

(numpy.ndarray, True)

La dimensione di un vettore è definito dalla suo attributo `shape`, il quale è una tupla di $n$ interi non-negativi che specifica il numero di elementi in ogni dimensione.

In [9]:
# a è un vettore 1-dimensionale con 3 elementi
vettore.shape

(3,)

In [10]:
# b è un vettore 2-dimensionale (matrice) con 2 righe e 3 colonne
matrice = np.array([(1, 2, 3), (4, 5, 6)])
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
type(matrice)

numpy.ndarray

In [12]:
matrice.shape

(2, 3)

L'attributo `dtype` contiene il tipo degli oggetti contenuti nel vettore.

In [13]:
# Vettore contiene interi in base 64
vettore.dtype

dtype('int64')

In [14]:
vettore_float = np.array([1.2, 2.5, 7.8])
vettore_float

array([1.2, 2.5, 7.8])

In [15]:
# È sempre un'istanze di ndarray
type(vettore_float)

numpy.ndarray

In [16]:
# Ma il suo dtype è float64 
vettore_float.dtype

dtype('float64')

Il `dtype` può essere specificato quando si inizializza un oggetto di tipo `ndarray`

In [17]:
# Senza specificare il dtype sarebbe int 
# ma forziamo la conversione a float
vettore_float = np.array([0, 1, 2], dtype = float)

In [18]:
vettore_float

array([0., 1., 2.])

In [19]:
vettore_float.dtype

dtype('float64')

NumPy mette a disposizone parecchie funzioni per creare vettori speciali.

`numpy.zeros(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, con tutti gli elementi uguali a zero.

In [21]:
mat = np.zeros(2, 2)

TypeError: Cannot interpret '2' as a data type

In [22]:
# Una matrice 2x2 di zeri con dtype float 
mat = np.zeros((2, 2))
print(mat, mat.shape, mat.dtype)

[[0. 0.]
 [0. 0.]] (2, 2) float64


`numpy.ones(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, con tutti gli elementi uguali a uno.

In [23]:
# Una matrice 3x4 di zeri con dtype int 
mat = np.ones((3, 4), dtype = int)
print(mat, mat.shape, mat.dtype)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]] (3, 4) int64


`numpy.empty(shape, dtype)` restituisce un nuovo vettore avente una certa shape e dtype, senza inizializzare gli elementi.

In [26]:
# Una matrice 3x4 di elementi non inizializzati con dtype float 
e = np.empty((4, 1))
e[0]

array([4.79405002e-310])

Comunemente anche se la classe `ndarray` permette di istanziare vettori di 
ogni dimensione tipicamente ci si riferisce alle diverse dimensioni in modo diverso:

- 0D: scalare
- 1D: vettore
- 2D: matrice
- 3D+: tensore

In [27]:
# Un tensore 2x3x4 con tutti gli elementi a 1
tensore = np.ones((2, 3, 4))
tensore

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Gli oggetti di tipo `ndarray` possono essere indicizzati con la sintassi standard di Python, ovvero `array[index]` come nel caso delle liste.

In [28]:
vettore

array([1, 2, 3])

In [29]:
# L'elemento di posto 0
vettore[0]

1

In [30]:
# Gli elementi dal secondo in poi
vettore[1:]

array([2, 3])

In [31]:
matrice

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
# L'elemento di posto 0 è la prima riga
matrice[0]

array([1, 2, 3])

In [33]:
# L'elemento di posto 1 è la seconda riga
matrice[1]

array([4, 5, 6])

In [34]:
# Per estrarre un solo elemento dobbiamo usare due indici 
# uno per ogni dimensione
matrice[0][1]

2

In [35]:
# Equivalentemente in una sola parentesi
matrice[0, 1]

2

In [36]:
# Estrae la seconda colonna della matrice
matrice[:, 1]

array([2, 5])

In [39]:
# Estrae la prima riga della matrice
matrice[0, :]

array([1, 2, 3])

In [41]:
# Estrae la sottomatrice data dalla seconda e terza colonna
matrice[:, 1:3]

array([[2, 3],
       [5, 6]])

In [42]:
# Estrae la sottomatrice data dalla seconda e terza colonna
matrice[:, 1:]

array([[2, 3],
       [5, 6]])

Con gli `ndarrray` si possono eseguire anche indicizzazioni più complesse per esempio usando le liste.

In [43]:
vettore

array([1, 2, 3])

In [44]:
# Nuovo vettore che contiene gli elementi estratti 
# da vettore usando gli indici della lista
vettore[[0, 0, 1, 0]]

array([1, 1, 2, 1])

In [45]:
l = [1, 2, 3]

In [46]:
l[1:]

[2, 3]

In [47]:
l[0]

1

In [48]:
# La stessa cosa non si può fare con le liste
l[[0, 0, 1, 0]]

TypeError: list indices must be integers or slices, not list

In [51]:
vettore >= 2

array([False,  True,  True])

In [52]:
vettore[vettore >= 2]

array([2, 3])

Ai vettori si possono applicare gli operaratori di confronto: se si confronta un vettore con uno scalare si ottiene un vettore contenente i confronti elemento per elemento.

In [53]:
x = np.array([20, 30, 40, 50])
x

array([20, 30, 40, 50])

In [54]:
x > 35

array([False, False,  True,  True])

Vettori boolenni come quello appena ottenuto possono a loro volta essere usati per indicizzare un vettore della medesima dimesione.

In [55]:
# Estraiamo il sottovettore degli elementi maggiori di 35
x[x > 35]

array([40, 50])

In [56]:
# Stessa cosa con una lista di booleani
x[[False, False,  True,  True]]

array([40, 50])

È possibile assegare un valore ad un sottoinsieme di un `ndarray`

In [57]:
tensore

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [58]:
tensore[0, 0, 2] = 5
tensore

array([[[1., 1., 5., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [59]:
tensore[0, 0, 2:] = 5
tensore

array([[[1., 1., 5., 5.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [60]:
tensore[0, 0:2, 2:] = 5
tensore

array([[[1., 1., 5., 5.],
        [1., 1., 5., 5.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

[`numpy.arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html) è l'analogo in Numpy di `range`.

In [61]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
list(range(0, 10, 2))

[0, 2, 4, 6, 8]

In [64]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

`numpy.linspace(a, b, n)` restituisce un vettore avente un specifico numero di elementi `n` equispaziati su un certo intervallo [`a`,`b`].

In [65]:
np.linspace(0, 10, 2)

array([ 0., 10.])

In [66]:
np.linspace(0, 8, 5)

array([0., 2., 4., 6., 8.])

Di deafult il valore di `b` è incluso con `endpoint=False` si ottiene il seguente risultato.

In [67]:
np.linspace(0, 8, 5, endpoint = False)

array([0. , 1.6, 3.2, 4.8, 6.4])

In [68]:
np.linspace(0, 8, 7)

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

### Operazioni fra vettori

Con gli `ndarray` si possono eseguire tutte le operazioni dell'algebra vettoriale.

In [69]:
v1 = np.array([1, 2, 3])
v2 = np.array([1.2, 2.5, 7.8])

Sommando due vettori si ottiene la somma vettoriale fra i due che differeisce da quanto visto per le liste

In [73]:
v1 + v2

array([ 2.2,  4.5, 10.8])

In [71]:
list(v1) + list(v2)

[1, 2, 3, 1.2, 2.5, 7.8]

Per sommare due liste come se fossero vettori dovremmo usare un ciclo for o una list comprehension

In [ ]:
somma = []
for i in range(len(v1)):
    somma.append(v1[i] + v2[i])
somma

In [72]:
[v1[i] + v2[i] for i in range(len(v1))]

[2.2, 4.5, 10.8]

Come la somma tutte le altre opeazioni aritmetiche vengono eseguite elemento per elemento

In [74]:
v1 * v2

array([ 1.2,  5. , 23.4])

In [75]:
v1 - v2

array([-0.2, -0.5, -4.8])

In [76]:
v1 / v2

array([0.83333333, 0.8       , 0.38461538])

In [77]:
vettore

array([1, 2, 3])

In [78]:
matrice

array([[1, 2, 3],
       [4, 5, 6]])

Fintanto che le shape di due vettori sono compatibili anche se non uguali gli operatori aritmetici continuano ad essere utilizzabili con risultati spesso utili

In [79]:
print(matrice.shape, vettore.shape)

(2, 3) (3,)


Qui vettore viene considerato come vettore riga (shape = (1, 3)) e quindi la sottrazzione funziona per righe poiché le dimensioni di colonna coincidono.

In [80]:
# sottraiamo (2, 3) con (1, 3)
matrice - vettore

array([[0, 0, 0],
       [3, 3, 3]])

In [81]:
# Invece le shape (3, 3) e (2, 3) non sono compatibili
np.zeros((3, 3)) - np.zeros((2, 3))

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

NumPy include al suo interno diverse costanti predefinite, come `Inf` e `pi`.

In [82]:
np.pi

3.141592653589793

In [84]:
np.Inf

inf

In [85]:
type(np.Inf)

float

In [83]:
np.e

2.718281828459045

Al suo interno poi troviamo le funzioni matematematiche per esempio quelle trigonometriche quali $\sin(x)$ e $\cos(x)$.

In [86]:
np.cos(0)

1.0

In [87]:
np.sin(0)

0.0

Come abbiamo detto le operazioni aritmetiche lavorano elemento per elemento. 
Ma nel caso delle matrici il prodotto matriciale non è quello elemento per elemento.

In algebra lineare se due matrici $A$ di dimensioni $n\times m$ e $B$ di dimensioni 
$m \times p$ vengono moltiplicate la matrice prodotto di dimensioni $n\times p$ si calcola con
$$
(A \cdot B)_{ij} = \biggl(\sum_{k=1}^m a_{ik} b_{kj}\biggr) 
$$

In [88]:
# Definiamo due matrici 2x2
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

In [89]:
A, B

(array([[1, 1],
        [0, 1]]),
 array([[2, 0],
        [3, 4]]))

In [90]:
A + B

array([[3, 1],
       [3, 5]])

\* produce il prodotto elemento per elemento (se le shape sono compatibili)

In [91]:
A * B

array([[2, 0],
       [0, 4]])

@ produce il prodotto matriciale (se le matrici sono moltiplicabili)

In [92]:
A @ B

array([[5, 4],
       [3, 4]])

La stessa cosa si può ottenere anche con le funzioni `matmul` o `dot` del modulo NumPy

In [93]:
np.matmul(A, B)

array([[5, 4],
       [3, 4]])

In [94]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

Nel caso di vettori dimensionali con $n$ elementi invece `dot` restituisce il prodotto scalare
$$
<a, b> = \sum_{i=1}^n a_i b_i
$$

In [95]:
np.dot(v1, v2)

29.599999999999998

Nella libreria sono poi definite molte funzioni (che possono essere chiamate anche come metodi delle istaze di `ndarray`) per il calcolo di funzioni di natura statistica.

In [96]:
# Minimo
np.min(vettore), vettore.min()

(1, 1)

In [97]:
# Massimo
np.max(vettore), vettore.max()

(3, 3)

In [98]:
# Media aritmetica
np.mean(vettore), vettore.mean()

(2.0, 2.0)

In [99]:
# Deviazione standard
np.std(vettore), vettore.std()

(0.816496580927726, 0.816496580927726)

In [100]:
# Varianza
np.var(vettore), vettore.var()

(0.6666666666666666, 0.6666666666666666)

Per esempio la funzione che calcola la mediana invece non è disponibile come metodo di classe poiché in generale non è definita per i vettori multidimensionali.

In [103]:
vettore.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [101]:
np.median(vettore)

2.0

Il metodo `reshape` cambia la shape del vettore senza cambiare i dati contenuti in esso.

In [104]:
vec = np.arange(12)
vec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [105]:
vec.shape

(12,)

In [106]:
# Cambiamo la shape di vec da (12, 1) a (3, 4)
mat = vec.reshape(3, 4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [107]:
mat.shape

(3, 4)

In [109]:
mat.sum()

66

I metodi `min`, `max`, `sum`... possono essere calcolati solo su alcune dimensioni di un `ndarray`.

In [110]:
# Somma per colonne ovvero lungo la prima dimensione
mat.sum(axis = 0)

array([12, 15, 18, 21])

In [111]:
# Somma per righe ovvero lungo la seconda dimensione
mat.sum(axis = 1)

array([ 6, 22, 38])

Si può passare -1 al metodo reshape per far calcolare a NumPy il numero di elementi in quella dimensione

In [112]:
# Vogliamo mat con una shape di una sola dimensione quindi di 12 elementi
vec2 = mat.reshape(-1)
vec2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [113]:
mat.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

`numpy.ravel` permette di 'appiattire' un array ad una sola dimansione.

In [114]:
# Equivalente a mat.reshape(-1)
np.ravel(mat)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Il modulo `random` che abbiamo già introdotto è usatro per la generazione di numeri pseudo casuali.

In [115]:
import random

In [116]:
random.randint(0, 10)

5

Anche NumPy ha un sottomodulo random che permette di generare vettori i cui elementi sono numeri pseuso casuali.

`numpy.random.normal(mean=0.0, std=1.0, shape)` genera vettori estratti da una distribuzione Gaussiana.
$$
\mathcal{N}(\mu, \sigma^2)
$$

In [119]:
# Vettore di dimensione 10 estratto da N(0,1) normale standard
np.random.normal(0, 1, 10)

array([-0.11951946, -0.14909092, -1.71429527, -0.67664993,  0.77747579,
        0.02863424,  0.77896594,  1.85927286, -0.85176017, -0.33821884])

In [122]:
mu = 4
sigma = 1

sample = np.random.normal(mu, sigma, 100)
sample

array([4.87523785, 6.49698273, 4.43243578, 4.46267761, 5.19250087,
       2.67850656, 4.45313579, 4.71725096, 5.50107519, 5.18535288,
       3.55750989, 4.06918764, 2.31702939, 2.76723574, 3.91480947,
       5.05919824, 5.10448261, 2.06052367, 3.44351573, 3.93312789,
       4.14993238, 4.95063339, 3.11260371, 5.72565251, 4.24963207,
       3.60453277, 4.32396624, 3.95255208, 5.7430622 , 5.64121993,
       4.36695807, 4.62974467, 4.36919094, 4.20871388, 4.28805129,
       5.0311449 , 2.3889092 , 0.91720551, 3.62633049, 1.17488808,
       3.36542054, 3.84091751, 4.36424869, 3.71984661, 3.77305853,
       4.65616227, 4.71274426, 5.01935087, 2.7006224 , 4.53144153,
       3.84901753, 4.53214696, 3.39161711, 3.74170807, 5.29506584,
       5.37739506, 4.57517471, 3.49598665, 4.79353573, 4.20775646,
       4.69595277, 4.55626226, 4.3579982 , 5.2845496 , 3.54589155,
       4.69395759, 3.02887843, 5.19841367, 4.43770976, 2.30749472,
       5.41144501, 4.27672328, 4.06527134, 3.62143396, 3.94712

Se calcoliamo le stime campionarie di media e deviazione standard otteniamo i risultati attesi

In [123]:
sample.mean(), sample.std()

(4.087088924666481, 0.953465340218444)

La stima diventa più precisa all'aumentare della dimensione del campione

In [124]:
sample = np.random.normal(mu, sigma, 10000)
sample.mean(), sample.std()

(3.993165331124216, 1.0003522729345204)

`random.uniform(low=0.0, high=1.0, size=None)` genera vettori estratti da una distribuzione Uniforme.
$$
\mathcal{U}([low, high))
$$

In [125]:
# Vettore di dimensione 10 estratto da U(0,1) normale standard
np.random.uniform(0, 1, 10)

array([0.57878137, 0.01500172, 0.70567847, 0.77540232, 0.45984344,
       0.60471023, 0.05264572, 0.79566683, 0.44009633, 0.63001017])

In [126]:
np.random.uniform(0, 1, (5, 5))

array([[0.90419426, 0.48378047, 0.25172385, 0.73856033, 0.62205505],
       [0.06662797, 0.39933849, 0.31788905, 0.96035531, 0.04675475],
       [0.61244636, 0.43753161, 0.92668383, 0.21999017, 0.19250672],
       [0.84048844, 0.63760507, 0.8334327 , 0.1726377 , 0.46228819],
       [0.6728987 , 0.76269434, 0.11356128, 0.67019977, 0.9790657 ]])

## Esercizi

Definire la funzione `inversa`. Tale funzione prende in ingresso una matrice e 
- per prima cosa controlla che sia una matrice e che sia quadrata, altrimenti restituisce un errore e termina la funzione restituendo `None`. 
- calcola il determinante della matrice con la funzione `numpy.linalg.det(matrice)`
- se il determinante è maggiore di 0.0001 calcola la matrice inversa con la funzione `numpy.linalg.inv(matrice)` e la restituisce come output.

In [127]:
def inversa(matrice):
    # Controlliamo che matrice sia un ndarray
    if isinstance(matrice, np.ndarray):
        pass
    else:
        print("L'input deve essere un ndarray")
        return None
    # Controllare che sia una matrice e che sia quadrata
    if len(matrice.shape) == 2:
        if matrice.shape[0] == matrice.shape[1]:
            pass
        else:
            print("L'input deve essere una matrice quadrata (righe == colonne)")
            return None
    else:
        print("L'input deve essere una matrice (2 dimensioni)")
        return None

    determinante = np.linalg.det(matrice)

    if determinante > 0.0001:
        inv = np.linalg.inv(matrice)
        return inv
    else:
        print("La matrice non è invertibile (det < 0.0001)")
        return None

In [129]:
risultato = inversa("matrice")
print(risultato)

L'input deve essere un ndarray
None


In [130]:
risultato = inversa(np.array([1,2,3,4,5]))
print(risultato)

L'input deve essere una matrice (2 dimensioni)
None


In [131]:
risultato = inversa(np.array([1,2,3,4,5,6]).reshape(2, -1))
print(risultato)

L'input deve essere una matrice quadrata (righe == colonne)
None


In [132]:
risultato = inversa(np.array([1,2,3,4,5,6,7,8,9]).reshape(3, -1))
print(risultato)

La matrice non è invertibile (det < 0.0001)
None


In [137]:
matrice = np.array([1,0,-3,4,0,6,0,-1,9]).reshape(3, -1)
risultato = inversa(matrice)
print(risultato)
# Prova che sia l'inversa
print((matrice @ risultato).round(2))
# Il prodotto elemento per elemento non da lo stesso risultato
print((matrice * risultato).round(2))

[[ 0.33333333  0.16666667  0.        ]
 [-2.          0.5        -1.        ]
 [-0.22222222  0.05555556 -0.        ]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
[[ 0.33  0.   -0.  ]
 [-8.    0.   -6.  ]
 [-0.   -0.06 -0.  ]]


Definite le matrici e i vettori
$$
A = \begin{pmatrix}
    0 & 1 & 2\\
    -1 & 2 & 1\\
    1 & 0 & -2\\
    \end{pmatrix}\quad
B = \begin{pmatrix}
3 & 2\\
0 & -1\\
1 & 1 \\
\end{pmatrix}\quad
v = \begin{pmatrix}
1\\
-1\\
1 \\
\end{pmatrix}\quad
w = \begin{pmatrix}
0\\
-1\\
2 \\
\end{pmatrix}
$$
calcolare $AB$, $Av$, $Av + w$ e $<Av, Aw>$

In [144]:
A = np.array([[0, 1, 2], [-1, 2, 1], [1, 0, -2]])
B = np.array([[3, 2], [0, -1], [1, 1]])
v = np.array([1, -1, 1]).reshape(-1, 1)
#v = np.array([[1], [-1], [1]])
w = np.array([0, -1, 2]).reshape(-1, 1)

In [148]:
# AB
A @ B
np.matmul(A, B)

array([[ 2,  1],
       [-2, -3],
       [ 1,  0]])

In [150]:
# Av
A @ v

array([[ 1],
       [-2],
       [-1]])

In [151]:
# Av + w
A @ v + w

array([[ 1],
       [-3],
       [ 1]])

In [156]:
print(A @ v,  A @ w)
np.dot((A @ v).reshape(-1), (A @ w).reshape(-1))

[[ 1]
 [-2]
 [-1]] [[ 3]
 [ 0]
 [-4]]


7

Istanziare un tensore di dimensioni (5, 3, 3) le cui entrate sono estratte da una distribuzione normale standard.

Dopodiché sostituire tutti e soli i valori negativi con 0.

Calcolare media, varianza e mediana del tensore ottenuto.

Scrivere una funzione che:
- prende in ingresso una matrice $X$ di dimensione ($n$, $m$)
- restituisce una matrice $Y$ di dimensione ($n$, 2) contenente le medie e le varianza per riga di $X$.

Creare una classe `Titolo` che rappresenta un titolo misurato anno per anno. La classe dovrà avere i seguenti attributi:
- `nome`: string, nome del titolo
- `titolo`: numpy.array, vettore contenente le rilevazioni del titolo
- `periodo`: numpy.array, vettore contenente i periodi corrispondenti alle rilevazioni

e i seguenti metodi:
- `__len__` calcola la lunghezza del titolo.
- `indice_base_fissa(base)` che restituisce l'indice a base fissa calcolato con base il periodo `base`.
- `indice_base_mobile()` che restituisce l'indice a base mobile del titolo.
- `variazione_media(t1, t2)` che restituisce la variazione media del titolo fra il periodo `t1` e il periodo `t2`. 

Definire poi una funzione che, preso in ingresso un `Titolo` resituisca la matrice $M$ di dimensione ($n$, 4) con $n$ la lunghezza del titolo. La matrice $M$ contiene nella prima colonna il periodo, nella seconda il titolo, nella terza l'indice a base fissa (con base il primo periodo) e nella quarta l'indice a base mobile. 